export {default as Header} from './headers'
export {default as Home} from './home'
export {default as About} from './about'
export {default as Skill} from './skills'
export {default as Portfolio} from './portfolio'
export {default as Blog} from './blog'
export {default as Contact} from './contact'
export {default as Footer} from './footer'